version: "3"

services:
  app:
    container_name: dgg-piece
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3000"
    environment:
      # Secrets should be moved to .env on the server for security
      PAYLOAD_SECRET: "${PAYLOAD_SECRET}"
      NEXT_PUBLIC_SERVER_URL: "${NEXT_PUBLIC_SERVER_URL}"
      # SQLite database is used, so we don't need POSTGRES_URL
    volumes:
      - ./media:/app/media
      - ./dgg-piece.db:/app/dgg-piece.db

  tunnel:
    container_name: dgg-piece-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiMDVmY2E1OWRiYmExOGRmNWJiY2UxNmU0MTI2ZDMzYjAiLCJ0IjoiNzYyYTUzZDItNjFiZi00ODBjLThkODktYzlkM2ZlOTA0OWY1IiwicyI6IlptUmhaalprWldNdE1tUmlaaTAwTnpjM0xXRTVNMkl0WTJGaFkyVXpORFUzWlRjeCJ9
